# config/svhn_semi_supervised.yaml
seed: 42
device: cuda
log_dir: runs/svhn_semi/
save_model: true
save_dir: checkpoints/svhn/

# Dataset
dataset: SVHN
data_root: data/
num_classes: 10
image_size: 32
input_channels: 3

# Semi-supervised setup
semi_supervised: true
labeled_fraction: 0.0019  # 1000 of ~530000

# Model
hidden_dim: 1000
latent_dim: 20
style_dim: 20
use_gaussian_prior: true

# Training
epochs: 1000
batch_size: 100
noise_std: 0.2

# Optimizer
lr_reconstruction: 0.0001
lr_reconstruction_decay_epochs: [250]
lr_semi_supervised: 0.1
lr_adv: 0.01
lr_adv_decay_epochs: [250]
momentum_recon: 0.9
momentum_adv: 0.1

# Discriminator
disc_hidden_dim: 1000

# Evaluation
eval_interval: 50
parzen_num_samples: 10000