# config/unsupervised_clustering.yaml
seed: 42
device: cuda
log_dir: runs/mnist_clustering/
save_model: true
save_dir: checkpoints/mnist_clustering/

# Dataset
dataset: MNIST
data_root: data/
num_classes: 30
image_size: 28
input_channels: 1

# Semi-supervised setup
semi_supervised: false
labeled_fraction: 0.0

# Model
hidden_dim: 3000
latent_dim: 5
style_dim: 5
use_gaussian_prior: true

# Training
epochs: 1500
batch_size: 100
reconstruction_loss: mse
noise_std: 0.2

# Optimizer
lr_reconstruction: 0.01
lr_reconstruction_decay_epochs: [50]
lr_adv: 0.1
lr_adv_decay_epochs: [50]
momentum_recon: 0.9
momentum_adv: 0.1

# Discriminator
disc_hidden_dim: 1000

# Evaluation
eval_interval: 100
parzen_num_samples: 10000